[phases.build]
cmds = ["pnpm install --frozen-lockfile", "pnpm run build"]

[phases.start]
cmd = "pnpm run preview"

[variables]
NODE_VERSION = "20.18.0"
NODE_ENV = "production"
PNPM_VERSION = "9.15.9"

